//
// Copyright (c) 2003--2009
// Toon Knapen, Karl Meerbergen, Kresimir Fresl,
// Thomas Klimpel and Rutger ter Borg
//
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)
//
// THIS FILE IS AUTOMATICALLY GENERATED
// PLEASE DO NOT EDIT!
//

#ifndef BOOST_NUMERIC_BINDINGS_BLAS_LEVEL1_ROT_HPP
#define BOOST_NUMERIC_BINDINGS_BLAS_LEVEL1_ROT_HPP

#include <boost/mpl/bool.hpp>
#include <boost/numeric/bindings/blas/detail/blas.h>
#include <boost/numeric/bindings/traits/traits.hpp>
#include <boost/numeric/bindings/traits/type_traits.hpp>
#include <boost/static_assert.hpp>
#include <boost/type_traits/is_same.hpp>

namespace boost {
namespace numeric {
namespace bindings {
namespace blas {
namespace level1 {

// overloaded functions to call blas
namespace detail {
    inline void rot( integer_t const n, float* x, integer_t const incx,
            float* y, integer_t const incy, float const c, float const s ) {
        BLAS_SROT( &n, x, &incx, y, &incy, &c, &s );
    }
    inline void rot( integer_t const n, double* x, integer_t const incx,
            double* y, integer_t const incy, double const c, double const s ) {
        BLAS_DROT( &n, x, &incx, y, &incy, &c, &s );
    }
}

// value-type based template
template< typename ValueType >
struct rot_impl {

    typedef ValueType value_type;
    typedef typename traits::type_traits<ValueType>::real_type real_type;
    typedef void return_type;

    // templated specialization
    template< typename VectorX, typename VectorY >
    static return_type invoke( VectorX& x, VectorY& y, real_type const c,
            real_type const s ) {
        BOOST_STATIC_ASSERT( (boost::is_same< typename traits::vector_traits<
                VectorX >::value_type, typename traits::vector_traits<
                VectorY >::value_type >::value) );
        detail::rot( traits::vector_size(x), traits::vector_storage(x),
                traits::vector_stride(x), traits::vector_storage(y),
                traits::vector_stride(y), c, s );
    }
};

// low-level template function for direct calls to level1::rot
template< typename VectorX, typename VectorY >
inline typename rot_impl< typename traits::vector_traits<
        VectorX >::value_type >::return_type
rot( VectorX& x, VectorY& y, typename traits::vector_traits<
        VectorX >::value_type const c, typename traits::vector_traits<
        VectorX >::value_type const s ) {
    typedef typename traits::vector_traits< VectorX >::value_type value_type;
    rot_impl< value_type >::invoke( x, y, c, s );
}

}}}}} // namespace boost::numeric::bindings::blas::level1

#endif
